package net.minecraft.src;

public class BWG4LayerRiverMix extends GenLayer
{
    private GenLayer biomePatternGeneratorChain;
    private GenLayer riverPatternGeneratorChain;

    public BWG4LayerRiverMix(long var1, GenLayer var3, GenLayer var4)
    {
        super(var1);
        this.biomePatternGeneratorChain = var3;
        this.riverPatternGeneratorChain = var4;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long var1)
    {
        this.biomePatternGeneratorChain.initWorldGenSeed(var1);
        this.riverPatternGeneratorChain.initWorldGenSeed(var1);
        super.initWorldGenSeed(var1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.biomePatternGeneratorChain.getInts(var1, var2, var3, var4);
        int[] var6 = this.riverPatternGeneratorChain.getInts(var1, var2, var3, var4);
        int[] var7 = IntCache.getIntCache(var3 * var4);

        for (int var8 = 0; var8 < var3 * var4; ++var8)
        {
            if (var5[var8] != BiomeGenBase.BDocean.biomeID && var5[var8] != BiomeGenBase.BDtropicalisland.biomeID && var5[var8] != BiomeGenBase.BDjungleisland.biomeID && var5[var8] != BiomeGenBase.BDmushroomisland.biomeID)
            {
                if (var6[var8] >= 0)
                {
                    if (var5[var8] != BiomeGenBase.BDsnowpines.biomeID && var5[var8] != BiomeGenBase.BDsnowforest.biomeID && var5[var8] != BiomeGenBase.BDsnowtaiga.biomeID && var5[var8] != BiomeGenBase.BDsnowplains.biomeID && var5[var8] != BiomeGenBase.BDsnowhills.biomeID)
                    {
                        if (var5[var8] != BiomeGenBase.BDjungle.biomeID && var5[var8] != BiomeGenBase.BDswampland.biomeID)
                        {
                            if (var5[var8] != BiomeGenBase.BDdesert.biomeID && var5[var8] != BiomeGenBase.BDocean.biomeID && var5[var8] != BiomeGenBase.BDbeach.biomeID && var5[var8] != BiomeGenBase.BDbeachDunes.biomeID)
                            {
                                var7[var8] = BiomeGenBase.BDriver.biomeID;
                            }
                            else
                            {
                                var7[var8] = BiomeGenBase.BDsandriver.biomeID;
                            }
                        }
                        else
                        {
                            var7[var8] = BiomeGenBase.BDgreenriver.biomeID;
                        }
                    }
                    else
                    {
                        var7[var8] = BiomeGenBase.BDiceriver.biomeID;
                    }
                }
                else
                {
                    var7[var8] = var5[var8];
                }
            }
            else
            {
                var7[var8] = var5[var8];
            }
        }

        return var7;
    }
}
